[phases.setup]
nixPkgs = ["python311Full", "gcc"]

[phases.install]
cmds = [
  "python3.11 -m ensurepip --upgrade",
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
