[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python3.10 -m venv venv",
  "source venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python /app/bot.py"
